<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('games', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('mode')->default('dobleseis');
            $table->decimal('min_bet', 14, 2)->default(10);
            $table->unsignedTinyInteger('max_players')->default(4);
            $table->decimal('fee_percent', 5, 2)->default(10); // platform commission on the pot
            $table->boolean('active')->default(true);
            $table->timestamps();
        });

        Schema::create('game_tables', function (Blueprint $table) {
            $table->id();
            $table->foreignId('game_id')->constrained()->cascadeOnDelete();
            $table->string('name');
            $table->string('status')->default('open'); // open | playing | closed
            $table->timestamps();
        });

        Schema::create('matches', function (Blueprint $table) {
            $table->string('id')->primary();           // uuid generated by the game service
            $table->foreignId('game_id')->constrained();
            $table->string('status')->default('open'); // open | playing | finished | refunded
            $table->longText('players')->nullable();   // json [{id,name,user_id}]
            $table->unsignedBigInteger('winner_id')->nullable();
            $table->decimal('pot', 14, 2)->default(0);
            $table->decimal('fee_amount', 14, 2)->default(0);
            $table->decimal('prize', 14, 2)->default(0);
            $table->timestamp('started_at')->nullable();
            $table->timestamp('finished_at')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('matches');
        Schema::dropIfExists('game_tables');
        Schema::dropIfExists('games');
    }
};